Fix parsing of npm purls without namespace
package-url/packageurl-python pull request #106
Opened 2022-11-25 17:07 UTC by TG1999

Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

2022-11-25 17:54 UTC, pombredanne commented
You should update the GH workflows to drop 3.6 and add 3.11

2022-11-25 18:47 UTC, TG1999 commented
Thanks @pombredanne the CI tests are now running fine.

2022-11-28 16:45 UTC, pombredanne requested changes
Thanks for your consideration.

2022-11-28 16:45 UTC, pombredanne commented on src/packageurl/__init__.py
> +            namespace = ""
This is not needed

2022-11-28 16:45 UTC, pombredanne commented on src/packageurl/__init__.py
> +            name = ""
This is not needed either

2022-11-28 16:45 UTC, pombredanne commented on src/packageurl/__init__.py
> +            namespace, sep, name_version = path.partition("/")
```suggestion
            namespace, sep, path = path.partition("/")
```
and then just do not special case anymore and the new code added below

2022-11-28 19:05 UTC, TG1999 commented
We need name to be declared here https://github.com/package-url/packageurl-python/pull/106/files#diff-1ac2b399571df74798b2fbfab357ffa8cce45a332f1e69b6f1ccf86811d44ba6R394 , so we can error out here https://github.com/package-url/packageurl-python/pull/106/files#diff-1ac2b399571df74798b2fbfab357ffa8cce45a332f1e69b6f1ccf86811d44ba6R402

2022-12-28 11:06 UTC, pombredanne approved these changes
LGTM!
Thanks

2022-12-28 11:10 UTC, merged