Resolve Bugs in Github URLs
package-url/packageurl-python pull request #58
Opened 2021-01-25 05:48 UTC by TG1999

Signed-off-by: Tushar Goel <tushar.goel.dav@gmail.com>

2021-01-25 05:48 UTC, TG1999 commented
@tdruez FYI

2021-02-02 10:01 UTC, pombredanne requested changes
Thank you ++
See my comment inline for your consideration

2021-02-02 10:01 UTC, pombredanne commented on src/packageurl/contrib/url2purl.py
> +    for pattern in [archive_pattern, raw_pattern, blob_pattern, releases_download_pattern, download_pattern, git_pattern]:
What about using this?
```suggestion

    patterns = (
        archive_pattern,
        raw_pattern,
        blob_pattern,
        releases_download_pattern,
        download_pattern,
        git_pattern,
    )

    for pattern in patterns:
```

2021-02-02 10:02 UTC, TG1999 commented on src/packageurl/contrib/url2purl.py
> +    for pattern in [archive_pattern, raw_pattern, blob_pattern, releases_download_pattern, download_pattern, git_pattern]:
Agreed :)

2021-02-02 10:06 UTC, TG1999 commented
Done @pombredanne , please give it a look :)

2021-02-02 10:11 UTC, tdruez commented
@pombredanne We need your input on this discussing before approving those changes:
https://github.com/package-url/packageurl-python/issues/47#issuecomment-766548093

2021-10-05 09:30 UTC, merged